### ISSUE TITLE
For PCT 1.5.0

### ISSUE THREAD

**Issue by stannam** [PhonologicalCorpusTools/CorpusTools#754]
**1. For PCT 1.5** 

- [x] **Important: CHANGE THE VERSION NUMBER** (Follow this example: 30e0ec70aac873869946c1da484407e79163ef81 )
   - [x] For PCT (e.g., Help > Show version number...)    → update version number at `corpustools\__init__.py`
   - [x] For documentation (e.g., the copyright year at the buttom of each page) → `CorpusTools\docs\source\conf.py` and then change copyright year (lines 69-70) and version number (lines 76-79) 
   - [x] Create a new github branch '1.5.0'

**Bug fix**
- [x] Homophones in ND #785
- [x] using a column titled 'spelling' as transcription crashes PCT (#756) [not totally fixed, but warning message appears and is fine for release]
- [x] textgrid issues (#752)
- [x] pronunciation variants issues (#751) cf. we have a separate branch for this: 'pronunciation_variants' [pron.vars. in CSV is an enhancement, not a bug; okay for release]
    - [x]  pron.vars in two-lined interlinear corpus (cf. #787 -- we are not supporting pronunciation variants in 2-lined ilg)
- [x] phono search result should be cumulative (e.g., if the user conducts the same search many times, each search should generate a separate row in the result window.)
- [x] ipa2spe issues [solved!]

**Enhancement**
- [x] Additional filters for phonological search (Branch 'phono_search_improvement'). Make sure:
  - it works as intended
  - if reversed result window issue still exists on Mac (cf. #746)
- [x] #784

- [x] Syllabified example corpus

**Documentation**
- [x] Write up a new section for bigram selection, and update 'mutual information' and 'transitional probability' to refer to it.

- [x] Update screenshots 
  - Phonological search: 'Searches' windows
  - All results windows: column names changed **and additional filters added**

- [x] ~~"Working with transcriptions and feature systems":~~
  - ~~user generated 'SPE-like' feature system would be better to include 'cons'~~

- [x] Phonological search
  - Update 'Saving Searches' (Changed the way we save a search and 'Name this search' )
  - Update docs re: negative searches not being compatible with multiple environments

- [x] ~~Mutual information~~
  - ~~envrionment selection option~~
  - ~~in-word pairwise MI~~

- [x] ~~Transitional probability~~

- [x] ~~Loading in corpora > Saving and exporting a corpus or feature file~~
  - ~~add how to export a corpus with syllable delimiter~~

- [x] Write the release notes
- [x] Introduction page (version x.x differs from ... version y.y ... )

- [x] decide about command line utility -- add notes in documentation that say "Not actively supported with v. 1.5 and later"
- [ ] Functional load: 
  - optimization? (#733)
  - visualization? (#734)

**2. Not now**
- Uniqueness point calculation? (#753)
- Export tone and stress (#750)
- Change the way downloadable feature and corpus files are hosted
- A unified feature-transcription file
- Include syllables 
  - in environment selection dialogue box? (#732)
  - in analysis algorithms? (#694)
- Phonological search
  - corpus subset based on transcription? (#724)

**already fixed? or simply leave as 'known issues'?**
- "Can't download feature files" on macOS, Mojave version (10.14.6) #737
  - Unable to replicate this. (I remember it was a problem specific to a Mac version??) 
- can we close them??
  - "Example corpus crashes" #706 
  - Buckeye feature matrix #681 
  - Buckeye Corpus #677

**Comment by kchall** [comment]
For some reason, my cross-reference to the releases page on https://github.com/PhonologicalCorpusTools/CorpusTools/blob/master/docs/source/introduction.rst#id35 is not showing up as a link on https://corpustools.readthedocs.io/en/latest/introduction.html...I'm sure I've done something silly with the formatting.

**Comment by stannam** [comment]
@kchall It seems like :doc: instead of :ref: is used when referring to a file. 
The link is now working. 😊
https://corpustools.readthedocs.io/en/master/introduction.html
