### ISSUE TITLE
After v.1.5.0

### ISSUE THREAD

**Issue by stannam** [PhonologicalCorpusTools/CorpusTools#800]
This is a 'meta-' issue for tracking bugfixes and enhancements after v1.5.

**1. Bugs**

- [ ] importing the WebMaus TextGrids (tier settings on Mac, and pronunciation variants) #798 
- [x] PCT cannot import a UTF-16 file #799
  - Added a warning message when the user tries to import a UTF-16 file. (see screenshot on the issue page)

**2. Enhancement**

- [ ] #792 
  - @stannam is working on a separate branch 'variants_inv_chart'

- Analysis functions
  - [ ] Uniqueness point calculation? #753
  - [ ] visualization on FL outputs (and possibly ProD outputs, etc.) #734 
- Corpus
  - [ ] subsetting corpus based on transcription? (#724)
  - [ ] Export tone and stress (#750)
- Feature and transcription
  - [ ] Change the way downloadable feature and corpus files are hosted
  - [ ] A unified feature-transcription file
  - [ ] feature geometry? #795
- Syllables  
  - [ ] include syllables in environment selection dialogue box? (#732)
  - [ ] include syllables in analysis algorithms? (#694)
